import { Outfit } from "next/font/google";
import "./globals.css";
import ConvexClintprovider from "./ConvexClintprovider";

const outfit = Outfit({
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={outfit.className}
      >
        <ConvexClintprovider>
          {children}
        </ConvexClintprovider>
      </body>
    </html>
  );
}
